### ISSUE TITLE
Cannot read property '$el' of undefined

### ISSUE THREAD

**Issue by fproldan** [yunusga/OwlCarousel2-Rows#2]
Hi, i have the follow error:
Cannot read property '$el' of undefined  in line 21 (this.owl.dom.$el.on(this.handlers)

Thanks

**Comment by piermelatti** [comment]
Same problem here

**Comment by yunusga** [comment]
different api in the Owl Carousel 2 branches
`$el` works for master branch

**Comment by greenchapter** [comment]
I have this problem by using your script
TypeError: undefined is not an object (evaluating 'this.owl.dom.$el')

**Comment by yunusga** [comment]
https://github.com/yunusga/owl2rows/commit/4728d751c4f2ee0c5dd93d1e55472db561769f7e
