### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by piermelatti** [yunusga/OwlCarousel2-Rows#3]
Hi @gaziev 

I have a question for you. My content is paginating this way:
 1   2   3   4       5   6   7   8        9  10 11 12
13 14 15 16     17 18 19 20      21 22 23 24

And I want it to paginate like:
1   2   3   4       9  10 11 12       17 18 19 20
5   6   7   8      13 14 15 16       21 22 23 24

Is that a way to achieve that?

Thanks!

**Comment by yunusga** [comment]
https://t.co/ShsAZjQCkV
